apiVersion: v1
kind: ConfigMap
metadata:
  name: gatekeeper-custom-config
  namespace: kommander
data:
  values.yaml: |
    auditInterval: 300
    auditMatch:
      - excludedNamespaces:
        - kube-system
        - kommander
---
apiVersion: apps.kommander.d2iq.io/v1alpha3
kind: AppDeployment
metadata:
  name: gatekeeper
  namespace: kommander
spec:
  configOverrides:
    name: gatekeeper-custom-config
