apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  name: dev-sandbox
  namespace: development-fleet
spec:
  workspaceRef:
    name: development-fleet
  placement:
    clusterSelector:
      matchLabels:
        environment: development
