apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/gatekeeper-config.yaml
  - policies/require-labels-template.yaml
  - policies/require-labels-constraint.yaml 
patches:
  - path: apps/gatekeeper-patch.yaml
    target:
      kind: AppDeployment
      name: gatekeeper
      namespace: kommander