apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: Project
metadata:
  name: frontend-team
  namespace: production-fleet
spec:
  workspaceRef:
    name: production-fleet
  placement:
    # Federates this project to ALL clusters in the prod fleet with this label
    clusterSelector:
      matchLabels:
        environment: production
